<script>
    $(function () {
        $("#catchall_addresses_type_auto, #catchall_addresses_type_manual").on('change', function () {
            if ($(this).val() === 'auto' && $(this).is(':checked')) {
                $("#automatic_catchall_addresses").prop('disabled', false);
                $("#manual_catchall_addresses").prop('disabled', true).val('');
            } else if ($(this).val() === 'manual' && $(this).is(':checked')) {
                $("#automatic_catchall_addresses").prop('disabled', true);
                $("#manual_catchall_addresses").prop('disabled', false);
            }
        }).trigger('change');
    });
</script>
<form name="create_catchall_frm" method="post" action="mail_catchall_add.php?id={CATCHALL_ID}">
    <div class="form sectionBox horizontal">
        <header>
            <h3><?= tohtml(tr('Catch-all addresses for the %s domain', '{CATCHALL_DOMAIN}'));?></h3>
        </header>
        <section>
            <!-- BDP: automatic_catchall_addresses_blk -->
            <div class="form-element">
                <label class="radio" for="catchall_addresses_type_auto" data-tooltip="<?= tohtml(tr('You can select as many addresses as you want.'), 'htmlAttr') ;?>">
                    <input type="radio" name="catchall_addresses_type" id="catchall_addresses_type_auto" value="auto"{AUTOMATIC_CATCHALL_ADDRESSES_CHECKED}>
                    <span><?= tohtml(tr('Automatic catch-all addresses')) ;?></span>
                </label>
                <div>
                    <!--email_off-->
                    <select class="form-field" name="automatic_catchall_addresses[]" id="automatic_catchall_addresses" size='3' multiple required>
                        <!-- BDP: automatic_catchall_address_option -->
                        <option value="{AUTOMATIC_CATCHALL_ADDRESS_ID}">{AUTOMATIC_CATCHALL_ADDRESS}</option>
                        <!-- EDP: automatic_catchall_address_option -->
                    </select>
                    <!--/email_off-->
                </div>
            </div>
            <!-- EDP: automatic_catchall_addresses_blk -->
            <div class="form-element">
                <label class="radio" for="catchall_addresses_type_manual" data-tooltip="<?= tohtml(tr('Separate addresses by a comma, line-break or space.'), 'htmlAttr') ;?>">
                    <input type="radio" name="catchall_addresses_type" id="catchall_addresses_type_manual" value="manual"{MANUAL_CATCHALL_ADDRESSES_CHECKED}>
                    <span><?= tohtml(tr('Manual catch-all addresses'));?></span>
                </label>
                <textarea class="form-field" name="manual_catchall_addresses" id="manual_catchall_addresses" required>{MANUAL_CATCHALL_ADDRESSES}</textarea>
            </div>
            <div class="form-element">
                <div class="action">
                    <button name="Submit" type="submit" class="btn">
                        <?= tohtml(tr('Add'), 'htmlAttr'); ?>
                    </button>
                    <a href="mail_catchall.php" class="btn muted"><?= tohtml(tr('Cancel')); ?></a>
                </div>
            </div>
        </section>
    </div>
</form>
