<!-- BDP: mail_feature -->
<script>

    function action_delete(link, subject) {
        return jQuery.imscp.confirmOnclick(link, sprintf("<?= tojs(tr('Are you sure you want to delete this %%s account?')); ?>", subject));
    }

    $(function () {

        $('[data-dataTable]').find("tbody").on("click", "input[type=checkbox]:not(':disabled')", function () {
            $('[data-dataTable]').find("thead input[type=checkbox],tfoot input[type=checkbox]").prop('checked', ($(this).find("input[type=checkbox]:checked").length === $("tbody input[type=checkbox]:not(':disabled')").length));
        });

        $('[data-dataTable]').find("thead :checkbox, tfoot input[type=checkbox]").click(function (e) {
            if ($('[data-dataTable]').find("tbody input[type=checkbox]:not(':disabled')").length !== 0) {
                $('[data-dataTable]').find("input[type=checkbox]:not(':disabled')").prop('checked', $(this).is(':checked'));
            } else {
                e.preventDefault();
            }
        });

        $('input[type=submit]').click(function() {

            var input = this;
            input.blur();

            if($('input[type=checkbox]:checked').length < 1) {
                alert("<?= tojs(tr('You must select at least one mail account to delete.')); ?>");
                return false;
            }

            return jQuery.imscp.confirm("<?= tojs(tr('Are you sure you want to delete all selected mail accounts?')); ?>", function(ret) {
                if(ret) {
                    $(input).closest("form").submit();
                }
            });

        });
    });

</script>

<!-- BDP: mail_accounts -->
<form action="mail_delete.php" method="post">
    <div class="sectionBox table">
        <header>
            <h3>{TR_TITLE}</h3>
        </header>
        <table data-dataTable='<?=getDataTablesPluginTranslations(); ?>'>
            <thead class="middle">
                <th class="toggle">
                    <label class="checkbox noMargin">
                        <input type="checkbox">
                        <span></span>
                    </label>
                </th>
                <th><?= tohtml(tr('Mail')); ?></th>
                <th><?= tohtml(tr('Type')); ?></th>
                <th><?= tohtml(tr('Quota info')); ?></th>
                <th><?= tohtml(tr('Status')); ?></th>
                <th></th>
            </thead>
            <tbody>
                <!-- BDP: mail_account -->
                <tr>
                    <td class="toggle">
                        <label class="checkbox noMargin">
                            <input type="checkbox" name="id[]" value="{MAIL_ACCOUNT_ID}"{MAIL_ACCOUNT_DISABLED_DELETION_CHECKBOX}>
                            <span></span>
                        </label>
                    </td>
                    <td>
                        <!--email_off-->
                        <div>{MAIL_ACCOUNT_ADDR}</div>
                        <!--/email_off-->
                        <!-- BDP: mail_account_autoresponder -->
                        <small>
                            <?= tohtml(tr('Autoresponder')); ?>:
                            <!-- BDP: mail_account_autoresponder_activation_link -->
                            <a href="mail_autoresponder_enable.php?id={MAIL_ACCOUNT_ID}" class="icon i_reload" title="<?= tohtml(tr('Activate', 'htmlAttr')); ?>"><?= tohtml(tr('Activate')); ?></a>
                            <!-- EDP: mail_account_autoresponder_activation_link -->
                            <!-- BDP: mail_account_autoresponder_deactivation_link -->
                            <a href="mail_autoresponder_disable.php?id={MAIL_ACCOUNT_ID}" class="icon i_reload" title="<?= tohtml(tr('Deactivate', 'htmlAttr')); ?>"><?= tohtml(tr('Deactivate')); ?></a>
                            <!-- EDP: mail_account_autoresponder_deactivation_link -->
                            <a href="mail_autoresponder_edit.php?id={MAIL_ACCOUNT_ID}" class="icon i_edit" title="<?= tohtml(tr('Edit', 'htmlAttr')); ?>"><?= tohtml(tr('Edit')); ?></a>
                        </small>
                        <!-- EDP: mail_account_autoresponder -->
                    </td>
                    <td>
                        <strong>{MAIL_ACCOUNT_TYPE}</strong>
                        <!-- BDP: mail_account_forward_list -->
                        <!--email_off-->
                        <div class="tooltip-entry">
                            <span class="tooltip-circle" data-tooltip="{MAIL_ACCOUNT_LONG_FORWARD_LIST}">
                                <i data-eva="question-mark-circle"></i>
                            </span>
                            {MAIL_ACCOUNT_SHORT_FORWARD_LIST}
                        </div>
                        <!--/email_off-->
                        <!-- EDP: mail_account_forward_list -->
                    </td>
                    <td>
                        <!-- BDP: mail_account_no_quota_warning -->
                        {MAIL_ACCOUNT_QUOTA_INFO}
                        <!-- EDP: mail_account_no_quota_warning -->
                        <!-- BDP: mail_account_quota_warning -->
                        <span>{MAIL_ACCOUNT_QUOTA_INFO}</span>
                        <!-- EDP: mail_account_quota_warning -->
                    </td>
                    <td>{MAIL_ACCOUNT_STATUS}</td>
                    <td>
                        <!-- BDP: mail_account_action_links -->
                        <div class="action-column">
                            <div ref="dropdown" class="dropdown">
                                <span>
                                    <i></i>
                                </span>
                                <ul>
                                    <!-- BDP: mail_account_edit_link -->
                                    <li><a href="mail_edit.php?id={MAIL_ACCOUNT_ID}" title="<?= tohtml(tr('Edit'), 'htmlAttr'); ?>"><?= tohtml(tr('Edit')); ?></a></li>
                                    <!-- EDP: mail_account_edit_link -->
                                    <!-- BDP: mail_account_delete_link -->
                                    <li class="delete"><a href="mail_delete.php?id={MAIL_ACCOUNT_ID}" onclick="return action_delete(this, '<?= tojs(tr('mail')); ?>')" title="<?= tohtml(tr('Delete'), 'htmlAttr'); ?>"><?= tohtml(tr('Delete')); ?></a></li>
                                    <!-- EDP: mail_account_delete_link -->
                                    <!-- BDP: mail_catchall_account_delete_link -->
                                    <li class="delete"><a href="mail_catchall_delete.php?id={MAIL_ACCOUNT_ID}" onclick="return action_delete(this, '<?= tojs(tr('catch-all')); ?>')" title="<?= tohtml(tr('Delete'), 'htmlAttr'); ?>"><?= tohtml(tr('Delete')); ?></a></li>
                                    <!-- EDP: mail_catchall_account_delete_link -->
                                </ul>
                            </div>
                            <!-- BDP: mail_protected_mail_account -->
                            <span class="tooltip-circle" data-tooltip="<?=tohtml(tr('This mail account is protected against both edition and deletion.'), 'htmlAttr'); ?>">
                                <i data-eva="lock"></i>
                            </span>
                            <!-- EDP: mail_protected_mail_account -->
                        </div>
                        <!-- EDP: mail_account_action_links -->
                    </td>
                </tr>
                <!-- EDP: mail_account -->
            </tbody>
        </table>
        <footer class="align-right">
            <div><?=tohtml(tr('Total accounts: %s / %s', '{MAIL_TOTAL_MAIL_ACCOUNTS}', '{MAIL_ACCOUNTS_LIMIT}')); ?></div>
            <div class="align-right">
                <!-- BDP: mail_show_default_mail_accounts_link -->
                <a href="/client/mail_accounts.php?show_default_mail_accounts=1" title="<?=tohtml(tr('Show default mail accounts'), 'htmlAttr');?>" class="btn sm muted"><?=tohtml(tr('Show default mail accounts')) ;?></a>
                <!-- EDP: mail_show_default_mail_accounts_link -->
                <!-- BDP: mail_hide_default_mail_accounts_link -->
                <a href="/client/mail_accounts.php?show_default_mail_accounts=0" title="<?=tohtml(tr('Hide default mail accounts'), 'htmlAttr');?>" class="btn sm muted"><?=tohtml(tr('Hide default mail accounts')); ?></a>
                <!-- EDP: mail_hide_default_mail_accounts_link -->
                <!-- BDP: mail_sync_quota_info_link -->
                <a href="/client/mail_accounts.php?sync_quota_info=1" title="<?=tohtml(tr('Force synching of mailboxes quota info. Quota info are automatically synced every 5 minutes.'), 'htmlAttr');?>" class="btn sm muted"><?=tohtml(tr('Sync quota info')); ?></a>
                <!-- EDP: mail_sync_quota_info_link -->
                <!-- BDP: mail_delete_selected_items_button -->
                <input class="btn sm" type="submit" name="Submit" value="<?=tr('Delete selected mail accounts', 'htmlAttr');?>">
                <!-- EDP: mail_delete_selected_items_button -->
            </div>
        </footer>
    </div>
</form>
<!-- EDP: mail_accounts -->
<!-- EDP: mail_feature -->
