<!-- BDP: client_list -->
<div class="list sectionBox clients">
    <header>
        <h3><?=tohtml(tr('Customers')); ?></h3>
        <!-- BDP: client_domain_aliases_switch -->
        <div>
            <!-- BDP: client_domain_aliases_show -->
            <a href="" class="btn sm muted outline alias" data-action="show"><?=tohtml(tr('Show domain aliases')); ?></a>
            <!-- EDP: client_domain_aliases_show -->
            <!-- BDP: client_domain_aliases_hide -->
            <a href="" class="btn sm muted outline alias" data-action="hide"><?=tohtml(tr('Hide domain aliases')); ?></a>
            <!-- EDP: client_domain_aliases_hide -->
        </div>
        <!-- EDP: client_domain_aliases_switch -->
    </header>
    <div class="legend">
        <ul>
            <li><?=tohtml(tr('Status')); ?></li>
            <li><?=tohtml(tr('Username')); ?></li>
        </ul>
    </div>
    <ul>
        <!-- BDP: client_item -->
        <li>
            <!-- BDP: client_domain_status_ok -->
            <div class="status">
                <a href="domain_status_change.php?domain_id={CLIENT_DOMAIN_ID}" data-tooltip="{TR_CLIENT_STATUS_TOOLTIP}" class="{CLIENT_STATUS_CLASS}">
                    <i data-eva="checkmark-circle-2"></i>
                    <i data-eva="close-circle"></i>
                    <strong><?=tohtml(tr('Status')); ?></strong>
                </a>
            </div>
            <div class="user">
                <div>
                    {CLIENT_USERNAME}
                    <a href="http://{CLIENT_DOMAIN_URL}/" target="_blank" class="globe">
                        <i data-eva="globe-3"></i>
                    </a>
                </div>
                <small>
                    {CLIENT_CREATED_ON} <? if($_SESSION['user_type'] == 'admin'): ?>({CLIENT_CREATED_BY})<? endif; ?>
                </small>
            </div>
            <!-- EDP: client_domain_status_ok -->
            <!-- BDP: client_domain_status_not_ok -->
            <div class="status">
                <span data-tooltip="{TR_CLIENT_STATUS_TOOLTIP}" class="{CLIENT_STATUS_CLASS}">
                    <i data-eva="alert-circle"></i>
                    <i data-eva="refresh"></i>
                    <strong><?=tohtml(tr('Status')); ?></strong>
                </span>
            </div>
            <div class="user">
                <div>
                    {CLIENT_USERNAME}
                </div>
                <small>
                    {CLIENT_CREATED_ON} <? if($_SESSION['user_type'] == 'admin'): ?>({CLIENT_CREATED_BY})<? endif; ?>
                </small>
            </div>
            <!-- EDP: client_domain_status_not_ok -->
            <div class="action-column right-xs">
                <a href="change_user_interface.php?to_id={CLIENT_ID}" class="btn sm muted icon-xxs">
                    <i data-eva="swap"></i>
                    <span><?=tohtml(tr('Switch')); ?></span>
                </a>
                <div ref="dropdown" class="dropdown">
                    <span>
                        <i></i>
                    </span>
                    <ul>
                        <li><a href="domain_details.php?domain_id={CLIENT_DOMAIN_ID}"><?=tohtml(tr('Details')); ?></a></li>
                        <li><a href="user_edit.php?edit_id={CLIENT_ID}"><?=tohtml(tr('Edit')); ?></a></li>
                        <!-- BDP: client_restricted_links -->
                        <? if($_SESSION['user_type'] == 'reseller'): ?>
                        <li><a href="domain_edit.php?edit_id={CLIENT_DOMAIN_ID}"><?=tohtml(tr('Edit domain')); ?></a></li>
                        <? endif; ?>
                        <li class="delete"><a href="user_delete.php?user_id={CLIENT_ID}" onclick="return action_delete(this)"><?=tohtml(tr('Delete')); ?></a></li>
                        <!-- EDP: client_restricted_links -->
                    </ul>
                </div>
            </div>
        </li>
        <!-- BDP: client_domain_alias_blk -->
        <li>
            <div class="status">
                <span data-tooltip="<?=tohtml(tr('Domain alias')); ?>" class="alias">
                    <i data-eva="globe"></i>
                    <strong><?=tohtml(tr('Domain alias')); ?></strong>
                </span>
            </div>
            <div class="user">
                <div>
                    {CLIENT_DOMAIN_ALIAS}
                    <a href="http://{CLIENT_DOMAIN_ALIAS_URL}/" target="_blank" class="globe">
                        <i data-eva="globe-3"></i>
                    </a>
                </div>
            </div>
            <div></div>
        </li>
        <!-- EDP: client_domain_alias_blk -->
        <!-- EDP: client_item -->
        <!-- BDP: client_message -->
        <li class="full">
            <div class="message info"><?=tohtml(tr('No account found.')); ?></div>
        </li>
        <!-- EDP: client_message -->
    </ul>
    <footer>
        <!-- BDP: client_search_form -->
        <form action="users.php" method="post" name="search_user">
            <div>
                <label>
                    <span><?=tohtml(tr('Filter customers by')); ?></span>
                    <div class="form-select sm">
                        <select name="search_field">
                            <option value="anything"{CLIENT_NONE_SELECTED}><?=tohtml(tr('anything')); ?></option>
                            <option value="domain_name"{CLIENT_DOMAIN_NAME_SELECTED}><?=tohtml(tr('domain name')); ?></option>
                            <option value="lname"{CLIENT_FIRST_NAME_SELECTED}><?=tohtml(tr('first name')); ?></option>
                            <option value="lname"{CLIENT_LAST_NAME_SELECTED}><?=tohtml(tr('last name')); ?></option>
                            <option value="firm"{CLIENT_COMPANY_SELECTED}><?=tohtml(tr('company')); ?></option>
                            <option value="city"{CLIENT_CITY_SELECTED}><?=tohtml(tr('city')); ?></option>
                            <option value="state"{CLIENT_STATE_SELECTED}><?=tohtml(tr('state/province')); ?></option>
                            <option value="country"{CLIENT_COUNTRY_SELECTED}><?=tohtml(tr('country')); ?></option>
                            <? if($_SESSION['user_type'] == 'admin'): ?>
                            <option value="reseller_name"{CLIENT_RESELLER_NAME_SELECTED}><?=tohtml(tr('reseller name')); ?></option>
                            <? endif; ?>
                        </select>
                    </div>
                </label>
                <label>
                    <span><?=tohtml(tr('that match with')); ?></span>
                    <input class="form-field sm" name="search_value" type="text" value="{SEARCH_VALUE}" required disabled></label>
                <label>
                    <span><?=tohtml(tr('which status is')); ?></span>
                    <div class="form-select sm">
                        <select name="search_status" id="search_status">
                            <option value="anything"{CLIENT_ANYTHING_SELECTED}><?=tohtml(tr('anything')); ?></option>
                            <option value="ok"{CLIENT_OK_SELECTED}><?=tohtml(tr('ok')); ?></option>
                            <option value="disabled"{CLIENT_DISABLED_SELECTED}><?=tohtml(tr('suspended')); ?></option>
                            <option value="error"{CLIENT_ERROR_SELECTED}><?=tohtml(tr('error')); ?></option>
                        </select>
                    </div>
                </label>
                <input type="hidden" name="client_domain_aliases_switch" value="{CLIENT_DOMAIN_ALIASES_SWITCH_VALUE}">
                <button class="btn icon sm" name="Submit" type="submit">
                    <i data-eva="search"></i>
                </button>
            </div>
        </form>
        <script>
            <? if($_SESSION['user_type'] == 'reseller'): ?>
            function action_delete(link) {
                return jQuery.imscp.confirmOnclick(link, '<?= tojs(tr('Are you sure you want to delete this account?')); ?>');
            }
            <? endif; ?>
            $(function() {
                let form = $('form[name="search_user"]'),
                    field = form.find('[name="search_field"]'),
                    value = $('[name="search_value"]'),
                    alias = $('.list header .alias');
                field.on('change', function() {
                    if($(this).val() === 'anything') {
                        value.prop('disabled', true).val('').parent().hide();
                        return;
                    }
                    value.prop('disabled', false).parent().show();
                }).trigger('change');
                form.on('submit', e => {
                    if(field.val().trim() === 'anything' || value.val().trim() !== '') {
                        return true;
                    }
                    alert("<?= tojs(tr('Missing search criteria.')); ?>");
                    return false;
                });
                alias.on('click', e => {
                    e.preventDefault();
                    form.find('[name="client_domain_aliases_switch"]').val(alias.data('action'));
                    form.trigger('submit');
                });
            });
        </script>
        <!-- EDP: client_search_form -->
    </footer>
    <footer>
        <ul class="paginate">
            <li>
                <!-- BDP: client_scroll_prev -->
                <a class="btn sm" href="users.php?psi={CLIENT_PREV_PSI}">
                    <i data-eva="chevron-left"></i>
                    <?=tohtml(tr('Previous')); ?>
                </a>
                <!-- EDP: client_scroll_prev -->
                <!-- BDP: client_scroll_prev_gray -->
                <a class="btn disabled sm">
                    <i data-eva="chevron-left"></i>
                    <?=tohtml(tr('Previous')); ?>
                </a>
                <!-- EDP: client_scroll_prev_gray -->
            </li>
            <li>
                <!-- BDP: client_scroll_next_gray -->
                <a class="btn disabled sm">
                    <?=tohtml(tr('Next')); ?>
                    <i data-eva="chevron-right"></i>
                </a>
                <!-- EDP: client_scroll_next_gray -->
                <!-- BDP: client_scroll_next -->
                <a class="btn sm" href="users.php?psi={CLIENT_NEXT_PSI}">
                    <?=tohtml(tr('Next')); ?>
                    <i data-eva="chevron-right"></i>
                </a>
                <!-- EDP: client_scroll_next -->
            </li>
        </ul>
    </footer>
</div>
<!-- EDP: client_list -->
