<form method="post" action="password_update.php" autocomplete="off">
    <div class="form horizontal">
        <header>
            <h3><?=tohtml(tr('Login data')); ?></h3>
        </header>
        <section>
            <div class="form-element">
                <label for="password"><?=tohtml(tr('Password')); ?></label>
                <input name="admin_pass" id="password" type="password" value="" class="pwd_generator form-field" autocomplete="new-password" required>
            </div>
            <div class="form-element">
                <label for="cpassword"><?=tohtml(tr('Password confirmation')); ?></label>
                <input name="admin_pass_confirmation" id="cpassword" class="form-field" type="password" value="" autocomplete="new-password" required>
            </div>
            <div class="form-element">
                <div class="action">
                    <button class="btn" type="submit" name="Submit">
                        <?=tohtml(tr('Update')); ?>
                    </button>
                </div>
            </div>
        </section>
    </div>
</form>
