<form action="personal_change.php" method="post">
    <div class="form sectionBox horizontal">
        <header>
            <h3><?=tohtml(tr('Personal data')); ?></h3>
        </header>
        <section class="two-columns">
            <div class="form-element">
                <label for="fname"><?=tohtml(tr('First name')); ?></label>
                <input class="form-field" type="text" name="fname" id="fname" value="<?=tohtml($this->form->getValue('fname'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="lname"><?=tohtml(tr('Last name')); ?></label>
                <input class="form-field" type="text" name="lname" id="lname" value="<?=tohtml($this->form->getValue('lname'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="gender"><?=tohtml(tr('Gender')); ?></label>
                <div class="form-select">
                    <select id="gender" name="gender">
                        <option value="M"<?=$this->form->getValue('gender') == 'M' ? ' selected' : ''; ?>><?=tohtml(tr('Male')); ?></option>
                        <option value="F"<?=$this->form->getValue('gender') == 'F' ? ' selected' : ''; ?>><?=tohtml(tr('Female')); ?></option>
                        <option value="U"<?=$this->form->getValue('gender') == 'U' ? ' selected' : ''; ?>><?=tohtml(tr('Unknown')); ?></option>
                    </select>
                </div>
            </div>
            <div class="form-element">
                <label for="firm"><?=tohtml(tr('Company')); ?></label>
                <input class="form-field" type="text" name="firm" id="firm" value="<?=tohtml($this->form->getValue('firm'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="street1"><?=tohtml(tr('Street 1')); ?></label>
                <input class="form-field" type="text" name="street1" id="street1" value="<?=tohtml($this->form->getValue('street1'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="street2"><?=tohtml(tr('Street 2')); ?></label>
                <input class="form-field" type="text" name="street2" id="street2" value="<?=tohtml($this->form->getValue('street2'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="zip"><?=tohtml(tr('Zip/Postal code')); ?></label>
                <input class="form-field" type="text" name="zip" id="zip" value="<?=tohtml($this->form->getValue('zip'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="city"><?=tohtml(tr('City')); ?></label>
                <input class="form-field" type="text" name="city" id="city" value="<?=tohtml($this->form->getValue('city'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="state"><?=tohtml(tr('State/Province')); ?></label>
                <input class="form-field" type="text" name="state" id="state" value="<?=tohtml($this->form->getValue('state'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="country"><?=tohtml(tr('Country')); ?></label>
                <input class="form-field" type="text" name="country" id="country" value="<?=tohtml($this->form->getValue('country'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="email"><?=tohtml(tr('Email')); ?></label>
                <input class="form-field" type="text" name="email" id="email" value="<?=tohtml(decode_idna($this->form->getValue('email')), 'htmlAttr'); ?>" required>
            </div>
            <div class="form-element">
                <label for="phone"><?=tohtml(tr('Phone')); ?></label>
                <input class="form-field" type="text" name="phone" id="phone" value="<?=tohtml($this->form->getValue('phone'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="fax"><?=tohtml(tr('Fax')); ?></label>
                <input class="form-field" type="text" name="fax" id="fax" value="<?=tohtml($this->form->getValue('fax'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <div class="action">
                    <button class="btn" name="Submit" type="submit">
                        <?=tohtml(tr('Update'), 'htmlAttr'); ?>
                    </button>
                    <a href="profile.php" class="btn muted"><?=tohtml(tr('Cancel')); ?></a>
                </div>
            </div>
        </section>
    </div>
</form>
