<div class="table sectionBox">
    <header>
        <h3>{TR_ACCOUNT_SUMMARY}</h3>
    </header>
    <ul>
        <li>
            <div>{TR_USERNAME}</div>
            <div>{USERNAME}</div>
        </li>
        <li>
            <div>{TR_ACCOUNT_TYPE}</div>
            <div>{ACCOUNT_TYPE}</div>
        </li>
        <li>
            <div>{TR_REGISTRATION_DATE}</div>
            <div>{REGISTRATION_DATE}</div>
        </li>
    </ul>
</div>
