<script>
    $(function() {
        $.each(imscp_i18n.core.error_field_stack, (i, k) => {
            $('#' + k).css('border-color', 'var(--error)');
        });
        $('#ip_data').find('input').click(function(e) {
            if($(this).is('[readonly]')) {
                e.preventDefault();
                return false;
            }
        });
    });
</script>
<form name="editFrm" method="post" action="reseller_edit.php?edit_id={EDIT_ID}" autocomplete="off">
    <div class="form sectionBox horizontal">
        <header>
            <h3>{TR_TITLE}</h3>
        </header>
        <section class="two-columns">
            <h4><?=tohtml(tr('Login data')); ?></h4>
            <div class="form-element">
                <label><?=tohtml(tr('Username')); ?></label>
                <p class="static"><?=tohtml($this->form->getValue('admin_name'), 'htmlAttr'); ?></p>
            </div>
            <div class="form-element">
                <label for="email"><?=tohtml(tr('Email')); ?></label>
                <input class="form-field" type="text" name="email" id="email" value="<?= tohtml(decode_idna($this->form->getValue('email')), 'htmlAttr'); ?>" required>
            </div>
            <div class="form-element">
                <label for="password"><?=tohtml(tr('Password')); ?></label>
                <input class="form-field pwd_generator" type="password" name="admin_pass" id="password" value="" autocomplete="new-password">
            </div>
            <div class="form-element">
                <label for="cpassword"><?=tohtml(tr('Password confirmation')); ?></label>
                <input class="form-field" type="password" name="admin_pass_confirmation" id="cpassword" value="" autocomplete="new-password">
            </div>
            <!-- BDP: ips_block -->
            <h4>{TR_IP_ADDRESS}</h4>
            <div class="form-element">
                <label>{TR_ASSIGN}</label>
                <div>
                    <!-- BDP: ip_block -->
                    <label class="checkbox">
                        <input type="checkbox" name="reseller_ips[]" value="{IP_ID}"{IP_ASSIGNED}{IP_READONLY}>
                        <span>{IP_NUMBER} <small>{IP_STATUS}</small></span>
                    </label>
                    <!-- EDP: ip_block -->
                </div>
            </div>
            <!-- EDP: ips_block -->
            <h4>{TR_ACCOUNT_LIMITS}</h4>
            <div class="form-element">
                <label for="max_dmn_cnt">{TR_MAX_DMN_CNT}</label>
                <input class="form-field" type="number" name="max_dmn_cnt" id="max_dmn_cnt" min="0" value="{MAX_DMN_CNT}">
            </div>
            <div class="form-element">
                <label for="max_sub_cnt">{TR_MAX_SUB_CNT}</label>
                <input class="form-field" type="number" name="max_sub_cnt" id="max_sub_cnt" min="-1" value="{MAX_SUB_CNT}">
            </div>
            <div class="form-element">
                <label for="max_als_cnt">{TR_MAX_ALS_CNT}</label>
                <input class="form-field" type="number" name="max_als_cnt" id="max_als_cnt" min="-1" value="{MAX_ALS_CNT}">
            </div>
            <div class="form-element">
                <label for="max_mail_cnt">{TR_MAX_MAIL_CNT}</label>
                <input class="form-field" type="number" name="max_mail_cnt" id="max_mail_cnt" min="-1" value="{MAX_MAIL_CNT}">
            </div>
            <div class="form-element">
                <label for="max_ftp_cnt">{TR_MAX_FTP_CNT}</label>
                <input class="form-field" type="number" name="max_ftp_cnt" id="max_ftp_cnt" min="-1" value="{MAX_FTP_CNT}">
            </div>
            <div class="form-element">
                <label for="max_sql_db_cnt">{TR_MAX_SQL_DB_CNT}</label>
                <input class="form-field" type="number" name="max_sql_db_cnt" id="max_sql_db_cnt" min="-1" value="{MAX_SQL_DB_CNT}">
            </div>
            <div class="form-element">
                <label for="max_sql_user_cnt">{TR_MAX_SQL_USER_CNT}</label>
                <input class="form-field" type="number" name="max_sql_user_cnt" id="max_sql_user_cnt" min="-1" value="{MAX_SQL_USER_CNT}">
            </div>
            <div class="form-element">
                <label for="max_traff_amnt">{TR_MAX_TRAFF_AMNT}</label>
                <input class="form-field" type="number" name="max_traff_amnt" id="max_traff_amnt" min="0" max="17592186044416" value="{MAX_TRAFF_AMNT}">
            </div>
            <div class="form-element">
                <label for="max_disk_amnt">{TR_MAX_DISK_AMNT}</label>
                <input class="form-field" type="number" name="max_disk_amnt" id="max_disk_amnt" min="0" max="17592186044416" value="{MAX_DISK_AMNT}">
            </div>
            <h4>{TR_FEATURES}</h4>
            <div class="form-element">
                <label>{TR_PHP_EDITOR}</label>
                <div>
                    <label class="radio inline">
                        <input type="radio" name="php_ini_system" id="php_ini_system_yes" value="yes"{PHP_INI_SYSTEM_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="php_ini_system" id="php_ini_system_no" value="no"{PHP_INI_SYSTEM_NO}>
                        <span>{TR_NO}</span>
                    </label>
                    <button class="btn sm" type="button" id="php_editor_dialog_open">{TR_SETTINGS}</button>
                </div>
            </div>
            <div class="form-element">
                <label>{TR_SOFTWARES_INSTALLER}</label>
                <div>
                    <label class="radio inline">
                        <input type="radio" name="software_allowed" id="software_allowed_yes" value="yes"{SOFTWARES_INSTALLER_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="software_allowed" id="software_allowed_no" value="no"{SOFTWARES_INSTALLER_NO}>
                        <span>{TR_NO}</span>
                    </label>
                </div>
            </div>
            <div class="form-element">
                <label>{TR_SOFTWARES_REPOSITORY}</label>
                <div>
                    <label class="radio inline">
                        <input type="radio" name="softwaredepot_allowed" id="softwaredepot_allowed_yes" value="yes"{SOFTWARES_REPOSITORY_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="softwaredepot_allowed" id="softwaredepot_allowed_no" value="no"{SOFTWARES_REPOSITORY_NO}>
                        <span>{TR_NO}</span>
                    </label>
                </div>
            </div>
            <div class="form-element">
                <label>{TR_WEB_SOFTWARES_REPOSITORY}</label>
                <div>
                    <label class="radio inline">
                        <input type="radio" name="websoftwaredepot_allowed" id="websoftwaredepot_allowed_yes" value="yes"{WEB_SOFTWARES_REPOSITORY_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="websoftwaredepot_allowed" id="websoftwaredepot_allowed_no" value="no"{WEB_SOFTWARES_REPOSITORY_NO}>
                        <span>{TR_NO}</span>
                    </label>
                </div>
            </div>
            <div class="form-element">
                <label>{TR_SUPPORT_SYSTEM}</label>
                <div>
                    <label class="radio inline">
                        <input type="radio" name="support_system" id="support_system_yes" value="yes"{SUPPORT_SYSTEM_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="support_system" id="support_system_no" value="no"{SUPPORT_SYSTEM_NO}>
                        <span>{TR_NO}</span>
                    </label>
                </div>
            </div>
            <h4><?=tohtml(tr('Personal data')); ?></h4>
            <div class="form-element">
                <label for="fname"><?=tohtml(tr('First name')); ?></label>
                <input class="form-field" type="text" name="fname" id="fname" value="<?=tohtml($this->form->getValue('fname'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="lname"><?=tohtml(tr('Last name')); ?></label>
                <input class="form-field" type="text" name="lname" id="lname" value="<?=tohtml($this->form->getValue('lname'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="gender"><?=tohtml(tr('Gender')); ?></label>
                <div class="form-select">
                    <select id="gender" name="gender">
                        <option value="M"<?=$this->form->getValue('gender') == 'M' ? ' selected' : ''; ?>><?=tohtml(tr('Male')); ?></option>
                        <option value="F"<?=$this->form->getValue('gender') == 'F' ? ' selected' : ''; ?>><?=tohtml(tr('Female')); ?></option>
                        <option value="U"<?=$this->form->getValue('gender') == 'U' ? ' selected' : ''; ?>><?=tohtml(tr('Unknown')); ?></option>
                    </select>
                </div>
            </div>
            <div class="form-element">
                <label for="firm"><?=tohtml(tr('Company')); ?></label>
                <input class="form-field" type="text" name="firm" id="firm" value="<?=tohtml($this->form->getValue('firm'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="street1"><?=tohtml(tr('Street 1')); ?></label>
                <input class="form-field" type="text" name="street1" id="street1" value="<?=tohtml($this->form->getValue('street1'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="street2"><?=tohtml(tr('Street 2')); ?></label>
                <input class="form-field" type="text" name="street2" id="street2" value="<?=tohtml($this->form->getValue('street2'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="zip"><?=tohtml(tr('Zip/Postal code')); ?></label>
                <input class="form-field" type="text" name="zip" id="zip" value="<?=tohtml($this->form->getValue('zip'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="city"><?=tohtml(tr('City')); ?></label>
                <input class="form-field" type="text" name="city" id="city" value="<?=tohtml($this->form->getValue('city'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="state"><?=tohtml(tr('State/Province')); ?></label>
                <input class="form-field" type="text" name="state" id="state" value="<?=tohtml($this->form->getValue('state'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="country"><?=tohtml(tr('Country')); ?></label>
                <input class="form-field" type="text" name="country" id="country" value="<?=tohtml($this->form->getValue('country'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="phone"><?=tohtml(tr('Phone')); ?></label>
                <input class="form-field" type="text" name="phone" id="phone" value="<?=tohtml($this->form->getValue('phone'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element">
                <label for="fax"><?=tohtml(tr('Fax')); ?></label>
                <input class="form-field" type="text" name="fax" id="fax" value="<?=tohtml($this->form->getValue('fax'), 'htmlAttr'); ?>">
            </div>
            <div class="form-element full-width">
                <div class="action">
                    <button class="btn" name="Submit" type="submit">
                        <?=tohtml(tr('Update'), 'htmlAttr'); ?>
                    </button>
                    <a href="users.php" class="btn muted"><?=tohtml(tr('Cancel')); ?></a>
                </div>
            </div>
        </section>
    </div>
    <div id="php_editor_dialog" title="{TR_PHP_EDITOR_SETTINGS}">
        <div class="message-container">
            <div class="php_editor_error message success">
                <span id="php_editor_msg_default">{TR_FIELDS_OK}</span>
            </div>
        </div>
        <div class="form horizontal small-value">
            <div class="form-element">
                <label>
                    {TR_PHP_INI_AL_ALLOW_URL_FOPEN}
                    <span class="tooltip-circle" data-tooltip="{TR_PHP_INI_PERMISSION_HELP}">
                        <i data-eva="question-mark-circle"></i>
                    </span>
                </label>
                <div class="align-right">
                    <label class="radio inline">
                        <input type="radio" name="php_ini_al_allow_url_fopen" id="php_ini_al_allow_url_fopen_yes" value="yes"{PHP_INI_AL_ALLOW_URL_FOPEN_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="php_ini_al_allow_url_fopen" id="php_ini_al_allow_url_fopen_no" value="no"{PHP_INI_AL_ALLOW_URL_FOPEN_NO}>
                        <span>{TR_NO}</span>
                    </label>
                </div>
            </div>
            <div class="form-element">
                <label>
                    {TR_PHP_INI_AL_DISPLAY_ERRORS}
                    <span class="tooltip-circle" data-tooltip="{TR_PHP_INI_PERMISSION_HELP}">
                        <i data-eva="question-mark-circle"></i>
                    </span>
                </label>
                <div class="align-right">
                    <label class="radio inline">
                        <input type="radio" name="php_ini_al_display_errors" id="php_ini_al_display_errors_yes" value="yes"{PHP_INI_AL_DISPLAY_ERRORS_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="php_ini_al_display_errors" id="php_ini_al_display_errors_no" value="no"{PHP_INI_AL_DISPLAY_ERRORS_NO}>
                        <span>{TR_NO}</span>
                    </label>
                </div>
            </div>
            <!-- BDP: php_editor_disable_functions_block -->
            <div class="form-element">
                <label>
                    {TR_PHP_INI_AL_DISABLE_FUNCTIONS}
                    <span class="tooltip-circle" data-tooltip="{TR_PHP_INI_PERMISSION_HELP}">
                        <i data-eva="question-mark-circle"></i>
                    </span>
                </label>
                <div class="align-right">
                    <label class="radio inline">
                        <input type="radio" name="php_ini_al_disable_functions" id="php_ini_al_disable_functions_yes" value="yes"{PHP_INI_AL_DISABLE_FUNCTIONS_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="php_ini_al_disable_functions" id="php_ini_al_disable_functions_no" value="no"{PHP_INI_AL_DISABLE_FUNCTIONS_NO}>
                        <span>{TR_NO}</span>
                    </label>
                </div>
            </div>
            <!-- EDP: php_editor_disable_functions_block -->
            <!-- BDP: php_editor_mail_function_block -->
            <div class="form-element">
                <label>
                    {TR_PHP_INI_AL_MAIL_FUNCTION}
                    <span class="tooltip-circle" data-tooltip="{TR_PHP_INI_AL_MAIL_FUNCTION_HELP}">
                        <i data-eva="question-mark-circle"></i>
                    </span>
                </label>
                <div class="align-right">
                    <label class="radio inline">
                        <input type="radio" name="php_ini_al_mail_function" id="php_ini_al_mail_function_yes" value="yes"{PHP_INI_AL_MAIL_FUNCTION_YES}>
                        <span>{TR_YES}</span>
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="php_ini_al_mail_function" id="php_ini_al_mail_function_no" value="no"{PHP_INI_AL_MAIL_FUNCTION_NO}>
                        <span>{TR_NO}</span>
                    </label>
                </div>
            </div>
            <!-- EDP: php_editor_mail_function_block -->
            <h4>{TR_DIRECTIVES_VALUES}</h4>
            <div class="form-element">
                <label for="max_execution_time">{TR_MAX_EXECUTION_TIME}</label>
                <div class="form-group">
                    <input class="form-field" type="number" name="max_execution_time" id="max_execution_time" min="1" max="10000" value="{MAX_EXECUTION_TIME}">
                    <span>{TR_SEC}</span>
                </div>
            </div>
            <div class="form-element">
                <label for="max_input_time">{TR_MAX_INPUT_TIME}</label>
                <div class="form-group">
                    <input class="form-field" type="number" name="max_input_time" id="max_input_time" min="1" max="10000" value="{MAX_INPUT_TIME}">
                    <span>{TR_SEC}</span>
                </div>
            </div>
            <div class="form-element">
                <label for="memory_limit">{TR_MEMORY_LIMIT}</label>
                <div class="form-group">
                    <input class="form-field" type="number" name="memory_limit" id="memory_limit" min="1" max="10000" value="{MEMORY_LIMIT}">
                    <span>{TR_MIB}</span>
                </div>
            </div>
            <div class="form-element">
                <label for="post_max_size">{TR_POST_MAX_SIZE}</label>
                <div class="form-group">
                    <input class="form-field" type="number" name="post_max_size" id="post_max_size" min="1" max="10000" value="{POST_MAX_SIZE}">
                    <span>{TR_MIB}</span>
                </div>
            </div>
            <div class="form-element">
                <label for="upload_max_filesize">{TR_UPLOAD_MAX_FILESIZE}</label>
                <div class="form-group">
                    <input class="form-field" type="number" name="upload_max_filesize" id="upload_max_filesize" min="1"  max="10000" value="{UPLOAD_MAX_FILESIZE}">
                    <span>{TR_MIB}</span>
                </div>
            </div>
        </div>
    </div>
</form>
