<script>
    function action_delete(link) {
        return jQuery.imscp.confirmOnclick(
            link, "<?= tojs(tr('Are you sure you want to delete this account?')); ?>"
        );
    }
</script>

<!-- BDP: administrator_list -->
<div class="list">
    <div class="toolbar">
        <h3><?=tohtml(tr('Administrator')); ?></h3>
    </div>
    <div class="legend">
        <ul>
            <li><?=tohtml(tr('Username')); ?></li>
            <li><?=tohtml(tr('Created on')); ?></li>
            <li><?=tohtml(tr('Created by')); ?></li>
        </ul>
    </div>
    <ul>
        <!-- BDP: administrator_item -->
        <li>
            <div class="username">{ADMINISTRATOR_USERNAME}</div>
            <div class="created_on">{ADMINISTRATOR_CREATED_ON}</div>
            <div class="created_by">{ADMINISTRATPR_CREATED_BY}</div>
            <div>
                <a href="user_edit.php?edit_id={ADMINISTRATOR_ID}" class="btn sm muted"><?=tohtml(tr('Edit')); ?></a>
                <!-- BDP: administrator_delete_link -->
                <a href="user_delete.php?delete_id={ADMINISTRATOR_ID}" onclick="return action_delete(this)"><?=tohtml(tr('Delete')); ?></a>
                <!-- EDP: administrator_delete_link -->
            </div>
        </li>
        <!-- EDP: administrator_item -->
        <!-- BDP: administrator_message -->
        <li class="no">
            <div class="message info"><?=tohtml(tr('No account found.')); ?></div>
        </li>
        <!-- EDP: administrator_message -->
    </ul>
</div>
<!-- EDP: administrator_list -->

<!-- BDP: reseller_list -->
<div class="list">
    <div class="toolbar">
        <h3><?=tohtml(tr('Resellers')); ?></h3>
    </div>
    <div class="legend">
        <ul>
            <li><?=tohtml(tr('Username')); ?></li>
            <li><?=tohtml(tr('Created on')); ?></li>
            <li><?=tohtml(tr('Created by')); ?></li>
        </ul>
    </div>
    <ul>
        <!-- BDP: reseller_item -->
        <li>
            <div class="username">{RESELLER_USERNAME}</div>
            <div class="created_on">{RESELLER_CREATED_ON}</div>
            <div class="created_by">{RESELLER_CREATED_BY}</div>
            <div>
                <a href="change_user_interface.php?to_id={RESELLER_ID}" class="btn sm muted"><?=tohtml(tr('Switch')); ?></a>
                <div class="dropdown">
                    <span>
                        <i></i>
                    </span>
                    <ul>
                        <li><a href="reseller_edit.php?edit_id={RESELLER_ID}"><?=tohtml(tr('Edit')); ?></a></li>
                        <li class="delete"><a href="user_delete.php?delete_id={RESELLER_ID}" onclick="return action_delete(this)"><?=tohtml(tr('Delete')); ?></a></li>
                    </ul>
                </div>
            </div>
        </li>
        <!-- EDP: reseller_item -->
        <!-- BDP: reseller_message -->
        <li class="no">
            <div class="message info"><?=tohtml(tr('No account found.')); ?></div>
        </li>
        <!-- EDP: reseller_message -->
    </ul>
</div>
<!-- EDP: reseller_list -->

<!-- INCLUDE "../shared/partials/client_list.phtml" -->
